Pull Request test
BozidarStevic/playlist pull request #2
Opened 2024-01-24 08:50 UTC by BozidarStevic

2024-01-24 10:03 UTC, vladanskoko reviewed
test

2024-01-26 09:16 UTC, vladanskoko reviewed
Add description to Pull Request

2024-01-26 12:29 UTC, branimir-vujicic commented on src/main/java/com/project/playlist/controller/PlaylistVideoController.java
> +        try {
in no response, don't return anything - it will respond OK

2024-01-26 12:29 UTC, branimir-vujicic commented on src/main/java/com/project/playlist/service/impl/PlaylistServiceImpl.java
> +        Optional<Playlist> playlistOptional = playlistRepository.findById(playlistId);
simplify method

```
  return playlistRepository.findById(playlistId)
            .orElseThrow(() -> PlaylistNotFoundException(playlistId));
```

2024-01-26 12:29 UTC, branimir-vujicic commented on src/main/java/com/project/playlist/service/impl/PlaylistVideoServiceImpl.java
> +        for (PlaylistVideo pv : playlistVideoList) {
use java stream findFirst

2024-01-26 12:31 UTC, branimir-vujicic reviewed
- in no response, don't return anything - it will respond OK

- Use Error Controller
```

public class ControllerExceptionHandler extends ResponseEntityExceptionHandler {


    @ExceptionHandler(ServiceException.class)
    @ResponseBody
    public HttpEntity<ErrorResponse> handleServiceException(HttpServletRequest request, ServiceException cause) {
        log.error(ERROR_PROCESSING_REQUEST_TEMPLATE, "handleServiceException", cause.getClass(), cause);

        HttpStatus status = HttpStatus.INTERNAL_SERVER_ERROR;
        ResponseStatus responseStatus = AnnotationUtils.findAnnotation(cause.getClass(), ResponseStatus.class);
        if (responseStatus != null) {
            status = responseStatus.code();
        }
        return new ResponseEntity<>(ErrorResponse.builder().type(cause.getErrorType()).errorCode(cause.getErrorCode()).status(status).path(request.getRequestURI()).message(cause.getMessage()).build(), status);
    }



    @ExceptionHandler(Exception.class)
    @ResponseBody
    public HttpEntity<ErrorResponse> handleUnknownException(Exception cause) {
        log.error(ERROR_PROCESSING_REQUEST_TEMPLATE, cause.getClass(), cause);

        HttpStatus status = HttpStatus.INTERNAL_SERVER_ERROR;
        ResponseStatus responseStatus = AnnotationUtils.findAnnotation(cause.getClass(), ResponseStatus.class);
        if (responseStatus != null) {
            status = responseStatus.code();
        }
        return new ResponseEntity<>(ErrorResponse.builder().type(ErrorType.GENERAL_ERROR).errorCode(INTERNAL_ERROR).status(status).path("").message(cause.getMessage()).build(), status);
    }
    
```
    
    
    
service (business) exceptions shoud extend some common (ServiceException) exception

2024-01-26 12:49 UTC, branimir-vujicic commented on src/main/java/com/project/playlist/controller/PlaylistController.java
> -    public ResponseEntity<String> removeVideoFromPlaylist(@PathVariable Long playlistId, @PathVariable Long videoId) {
use void instead of ResponseEntity<String>

2024-01-26 12:49 UTC, branimir-vujicic commented on src/main/java/com/project/playlist/controller/PlaylistController.java
> +    public ResponseEntity<PlaylistDTO> getPlaylistById(@PathVariable Long playlistId) {
change signature to public `PlaylistDTO getPlaylist ...`

2024-01-26 12:55 UTC, branimir-vujicic commented on src/main/java/com/project/playlist/service/impl/PlaylistVideoServiceImpl.java
> +        playlistService.getPlaylistById(playlistId);
`        return playlistVideoRepository.findByPlaylistIdOrderByOrderNo(playlistId)
                                      .stream()
                                      .map(PlaylistVideo::getVideo)
                                      .collect(Collectors.toList());`

2024-01-29 10:07 UTC, vladanskoko commented on src/main/java/com/project/playlist/service/impl/PlaylistVideoServiceImpl.java
> +            if (pv.getVideo().getId().longValue() == videoId.longValue()) {
Use `pv.getVideo().getId().equals(videoId)` instead of getting `longValue()`

2024-01-29 10:07 UTC, vladanskoko commented on src/main/java/com/project/playlist/service/impl/PlaylistVideoServiceImpl.java
> +    @Transactional
Add `@Transactional` annotation to service class and remove it from method

2024-01-29 10:07 UTC, vladanskoko commented on src/main/java/com/project/playlist/service/impl/PlaylistVideoServiceImpl.java
> +        for (PlaylistVideo pv : playlistVideoList) {
Use Java stream

2024-01-29 13:31 UTC, branimir-vujicic commented on src/main/java/com/project/playlist/service/impl/PlaylistVideoServiceImpl.java
> +        for (PlaylistVideo pv : playlistVideoList) {
`        PlaylistVideo fromPlaylistVideo = playlistVideoList.stream().filter(pv -> pv.getOrderNo() == fromOrderNo).findFirst().orElseThrow();
        PlaylistVideo toPlaylistVideo = playlistVideoList.stream().filter(pv -> (pv.getOrderNo() == toOrderNo)).findFirst().orElseThrow();
        changeOrderTransactional(fromPlaylistVideo, playlistVideoList, fromOrderNo, toOrderNo);`

2024-01-29 14:23 UTC, vladanskoko commented on src/main/java/com/project/playlist/service/impl/PlaylistVideoServiceImpl.java
> +            System.out.println("Video with id " + videoId + " already exists in playlist.");
Remove `System.out.println()` and create new `VideoAlreadyExists` exception which you will throw here

2024-01-29 14:35 UTC, vladanskoko reviewed
```
public class ErrorCodes {
    public static final int GENERAL_ERROR = 10000;
    public static final int CHAT_GPT_RESPONSE_ERROR = 10001;
    public static final int REQUEST_TIMEOUT_ERROR = 10002;
    public static final int NO_CONNECTION_ERROR = 10003;
    public static final int RESPONSE_PARSING_ERROR = 10004;
    public static final int NOT_AUTHORIZED = 10005;
    public static final int INVALID_CREDENTIALS = 10006;

    public static final int NOT_FOUND = 10007;

}

```

```
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class ErrorResponse {

    @Builder.Default
    private int errorCode = ErrorCodes.GENERAL_ERROR;
    @Builder.Default
    private HttpStatus status = HttpStatus.BAD_REQUEST;
    @Builder.Default
    private ErrorType type = ErrorType.GENERAL_ERROR;
    @Builder.Default
    private String message = "Error";
    private String path;
    private Long id;
    @Builder.Default
    private List<String> errors = Collections.emptyList();
}
```

```
public enum ErrorType {

    GENERAL_ERROR("10001", "Unclassified error"),
    INTERNAL_SERVER_ERROR("10002", "Internal server error"),
    VALIDATION_ERROR("10003", "Validation error"),
    BAD_REQ_INVALID_PASSWORD("10004", "Invalid auth"),
    BAD_REQ_INVALID_AUTHORIZATION("10005", "Invalid auth"),
    FORBIDDEN("10006", "Forbidden"),
    SERVICE_ERROR("10007", "Unclassified error"),
    UNSUPPORTED_MEDIA_TYPE_ERROR("10008", "Unsupported channels type error"),
    HTTP_MESSAGE_NOT_READABLE_ERROR("10009", "Http message not readable"),
    HTTP_METHOD_NOT_SUPPORTED("10012", "Http method not supported"),
    DUPLICATE_KEY("10010", "Duplicate DB key"),
    NOT_FOUND("10011", "Resource not found"),
    CHAT_GPT_ERROR("10012", "ChatGPT error"),
    TIMEOUT_ERROR("10013", "Request timeout error"),
    RESPONSE_PARSING_ERROR("10014", "Response parsing error"),
    NO_CONNECTION_ERROR("10015", "No connection error");

    private final String code;
    private final String type;

    ErrorType(String code, String type) {
        this.code = code;
        this.type = type;
    }

    public String code() {
        return code;
    }

    public String type() {
        return type;
    }

}
```

2024-01-30 09:59 UTC, vladanskoko commented on src/main/java/com/project/playlist/config/ControllerExceptionHandler.java
> +        HttpStatus status = HttpStatus.NOT_FOUND;
Change to `HttpStatus.BAD_REQUEST` status

2024-01-30 09:59 UTC, vladanskoko commented on src/main/java/com/project/playlist/exceptions/ErrorType.java
> +//    INTERNAL_SERVER_ERROR("10001", "Internal server error"),
Remove commented code

2024-01-30 12:44 UTC, branimir-vujicic commented on src/main/java/com/project/playlist/service/impl/PlaylistVideoServiceImpl.java
> +        PlaylistVideo playlistVideo = playlistVideoRepository.findByPlaylistIdAndVideoId(playlistId, videoId)
extract method

2024-01-31 08:54 UTC, vladanskoko requested changes

2024-01-31 08:54 UTC, vladanskoko commented on src/test/java/com/project/playlist/service/impl/GetSortedVideosForPlaylistTest.java
> +public class GetSortedVideosForPlaylistTest {
Rename class to `PlaylistVideoServiceTest` since you will test whole unit in this class

2024-01-31 08:54 UTC, vladanskoko commented on src/test/java/com/project/playlist/service/impl/GetSortedVideosForPlaylistTest.java
> +        Playlist playlist = new Playlist();
Create objects using `Builder` class

2024-01-31 08:54 UTC, vladanskoko commented on src/test/java/com/project/playlist/service/impl/GetSortedVideosForPlaylistTest.java
> +        List<PlaylistVideo> playlistVideoList = new ArrayList<>(List.of(playlistVideo1, playlistVideo2, playlistVideo3));
Here you created sorted list already and in test you check if list is sorted. You can not be sure in that case that your method is working properly.

Create unordered playlist like this:
`List<PlaylistVideo> playlistVideoList = new ArrayList<>(List.of(playlistVideo13, playlistVideo1, playlistVideo2));`

and with this list perform tests

2024-01-31 13:47 UTC, BozidarStevic commented on src/test/java/com/project/playlist/service/impl/GetSortedVideosForPlaylistTest.java
> +        List<PlaylistVideo> playlistVideoList = new ArrayList<>(List.of(playlistVideo1, playlistVideo2, playlistVideo3));
This playlistVideoList is return value for mock playlistVideoRepositoryMock.findByPlaylistIdOrderByOrderNo(). That is why this list should be sorted by order number.

2024-01-31 15:29 UTC, vladanskoko commented on src/test/java/com/project/playlist/service/impl/PlaylistVideoServiceTest.java
> +
Remove empty lines in all tests

2024-02-01 11:58 UTC, vladanskoko commented on src/main/java/com/project/playlist/model/PlaylistVideo.java
> +//    @Override
Remove commented code

2024-02-01 13:53 UTC, branimir-vujicic commented on src/main/java/com/project/playlist/controller/PlaylistVideoController.java
> +    @PostMapping("/playlists/{playlistId}/videos/{videoId}")
rename path to

/playlist/{playlistId}/video/{videoId}

2024-02-01 13:53 UTC, branimir-vujicic commented on src/main/java/com/project/playlist/controller/PlaylistVideoController.java
> +    @GetMapping("/playlists/{playlistId}/videos/sort")
remove "/sort"

2024-02-01 13:53 UTC, branimir-vujicic commented on src/main/java/com/project/playlist/model/PlaylistVideo.java
> +    @Override
for hashCode and equals use fileds: id, orderNo, playlist.id and video.id

2024-02-01 13:53 UTC, branimir-vujicic commented on src/main/java/com/project/playlist/service/impl/VideoServiceImpl.java
> +        videoRepository.findByUrlAndUserId(videoRequest.getUrl(), user.getId())
extract

2024-02-01 13:53 UTC, branimir-vujicic commented on src/test/java/com/project/playlist/service/impl/PlaylistVideoServiceTest.java
> +
```
Map<Long, PlaylistVideo> database = new HashMap();
lenient().when(playlistVideoRepositoryMock.save(playlistVideoForSave)).thenAnswer(answer -> {
playlistVideoForSave.setId(savedId);
map.put(playlistVideoForSave.getId(), playlistVideoForSave);
retrurn playlistVideoForSave;
});
```

2024-02-06 08:33 UTC, vladanskoko commented on src/test/java/com/project/playlist/service/impl/PlaylistServiceTest.java
> +    void givenNonexistentUserAndPlaylistName_whenCreateEmptyPlaylist_thenThrowException() {
Add exception type in test name like:
`givenNonexistentUserAndPlaylistName_whenCreateEmptyPlaylist_thenThrowUserNotFoundException()`

2024-02-06 08:33 UTC, vladanskoko commented on src/test/java/com/project/playlist/service/impl/PlaylistServiceTest.java
> +    void givenNullUserIdAndPlaylistName_whenCreateEmptyPlaylist_thenThrowException() {
`givenNullUserIdAndPlaylistName_whenCreateEmptyPlaylist_thenThrowIllegalArgumentException()`

2024-02-06 08:33 UTC, vladanskoko commented on src/test/java/com/project/playlist/service/impl/PlaylistServiceTest.java
> +    void givenInvalidPlaylistId_whenGetPlaylistById_thenThrowException() {
`givenInvalidPlaylistId_whenGetPlaylistById_thenThrowPlaylistNotFoundException()`

2024-02-06 08:33 UTC, vladanskoko commented on src/test/java/com/project/playlist/service/impl/PlaylistServiceTest.java
> +    void givenNullPlaylistId_whenGetPlaylistById_thenThrowException() {
`givenNullPlaylistId_whenGetPlaylistById_thenThrowIllegalArgumentException()`

2024-02-06 08:33 UTC, vladanskoko commented on src/test/java/com/project/playlist/service/impl/UserServiceTest.java
> +    void givenNullUserRequest_whenRegisterUser_thenThrowException() {
Rename all exception tests according to previous comments

2024-02-06 08:33 UTC, vladanskoko commented on src/test/java/com/project/playlist/service/impl/UserServiceTest.java
> +        verify(userRepositoryMock, times(0)).findByUsername(anyString());
You have here duplicated code. Move this to separate method.

2024-02-06 08:33 UTC, vladanskoko commented on src/test/java/com/project/playlist/service/impl/VideoServiceTest.java
> +    void givenExistingVideoUrlForUser_whenCreateVideo_thenThrowException() {
Rename according previous comments

2024-02-06 08:33 UTC, vladanskoko commented on src/test/java/com/project/playlist/service/impl/VideoServiceTest.java
> +        verify(userServiceMock, times(1)).getUserById(anyLong());
Move duplicated code into separate method

2024-02-06 13:04 UTC, branimir-vujicic commented on src/main/java/com/project/playlist/model/PlaylistVideo.java
> +                    ", video=" + video.getId() +
video == null ? "" : ", (video=" + video.getId()) +

2024-02-06 13:04 UTC, branimir-vujicic commented on src/main/java/com/project/playlist/model/Video.java
> +                    ", playlistVideos=" + playlistVideos +
remove - circular reference

2024-02-06 13:04 UTC, branimir-vujicic commented on src/main/java/com/project/playlist/service/impl/VideoServiceImpl.java
> +        Optional<Video> videoOptional = getVideoByUrlAndUserId(videoRequest.getUrl(), user);
create method 

boolean existsVideoByUrlAndUserId(... )

2024-02-06 13:05 UTC, vladanskoko approved these changes

2024-02-08 09:35 UTC, branimir-vujicic approved these changes

2024-02-08 09:35 UTC, merged